create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text not null check (char_length(username) between 2 and 24),
  total_xp integer not null default 0 check (total_xp between 0 and 100000),
  completed_modules integer not null default 0 check (completed_modules between 0 and 15),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.module_progress (
  user_id uuid not null references auth.users(id) on delete cascade,
  module_id text not null,
  completed_stages integer not null default 0 check (completed_stages between 0 and 2),
  updated_at timestamptz not null default now(),
  primary key (user_id, module_id)
);

create table if not exists public.practice_attempts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  question_id text not null,
  answer text not null check (char_length(answer) <= 12000),
  score integer not null check (score between 0 and 100),
  feedback jsonb not null,
  created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.module_progress enable row level security;
alter table public.practice_attempts enable row level security;

drop policy if exists "Profiles are publicly readable" on public.profiles;
create policy "Profiles are publicly readable"
  on public.profiles for select
  to anon, authenticated
  using (true);

drop policy if exists "Users create their own profile" on public.profiles;
create policy "Users create their own profile"
  on public.profiles for insert
  to authenticated
  with check ((select auth.uid()) = id);

drop policy if exists "Users update their own profile" on public.profiles;
create policy "Users update their own profile"
  on public.profiles for update
  to authenticated
  using ((select auth.uid()) = id)
  with check ((select auth.uid()) = id);

drop policy if exists "Users read their own module progress" on public.module_progress;
create policy "Users read their own module progress"
  on public.module_progress for select
  to authenticated
  using ((select auth.uid()) = user_id);

drop policy if exists "Users create their own module progress" on public.module_progress;
create policy "Users create their own module progress"
  on public.module_progress for insert
  to authenticated
  with check ((select auth.uid()) = user_id);

drop policy if exists "Users update their own module progress" on public.module_progress;
create policy "Users update their own module progress"
  on public.module_progress for update
  to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

drop policy if exists "Users read their own attempts" on public.practice_attempts;
create policy "Users read their own attempts"
  on public.practice_attempts for select
  to authenticated
  using ((select auth.uid()) = user_id);

drop policy if exists "Users create their own attempts" on public.practice_attempts;
create policy "Users create their own attempts"
  on public.practice_attempts for insert
  to authenticated
  with check ((select auth.uid()) = user_id);

grant select on public.profiles to anon, authenticated;
grant insert, update on public.profiles to authenticated;
grant select, insert, update on public.module_progress to authenticated;
grant select, insert on public.practice_attempts to authenticated;
grant usage, select on sequence public.practice_attempts_id_seq to authenticated;

create or replace view public.leaderboard
with (security_invoker = true)
as
select username, total_xp, completed_modules
from public.profiles
order by total_xp desc, completed_modules desc, created_at asc;

grant select on public.leaderboard to anon, authenticated;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
declare
  requested_name text;
begin
  requested_name := coalesce(
    nullif(trim(new.raw_user_meta_data ->> 'username'), ''),
    split_part(coalesce(new.email, 'student'), '@', 1)
  );
  if char_length(requested_name) < 2 then
    requested_name := 'student';
  end if;

  insert into public.profiles (id, username)
  values (new.id, left(requested_name, 24))
  on conflict (id) do nothing;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
